### ISSUE TITLE
The "create a new one" hyperlink is not stable

### ISSUE THREAD

**Issue by linsharon** [catalyst/moodle-assignsubmission_maharaws#38]
Hi,
I installed this plugin. But on the assignment submission page, the "create a new one" hyperlink is not always directing the user to the Mahara page. Every time after refreshing the page, if I click on "create a new one", it will take turns to take me either to the Mahara front page or to the assignment home page (the landing page of the assignment activity where the user can click "Add submission" button).   
The "create a new one" hyperlink's format is like below:
xxxxxx/mod/assign/submission/maharaws/launch.php?id=463&url=https%3A%2F%2Fmahara.xxx.xxx.ac.jp%2F&sesskey=xxxxxxx

<img width="683" alt="2021-12-26_12-27-11" src="https://user-images.githubusercontent.com/785549/147398162-05921f46-e0bd-49ae-8953-8deef05c1f0a.png">

**Comment by danmarsden** [comment]
#40 identifies this issue as being fixed so I'm closing this one off, but please let me know if I've missed something!
