### ISSUE TITLE
Exception - Class 'assignsubmission_maharaws\moodle_exception' not found

### ISSUE THREAD

**Issue by linsharon** [catalyst/moodle-assignsubmission_maharaws#41]
This issue has been resolved and I documented the solution in the attached file.

The following bug happened after I configured everything and it was smooth for admin to create mahara assignment activity in a Moodle course. However, when I logged in as a teacher role, I could not create a mahara assignment activity due to the following error:

```
Exception - Class 'assignsubmission_maharaws\moodle_exception' not found
More information about this error
```

**Comment by dmitriim** [comment]
HI @linsharon !
Thank you for reporting this issue. Will you be able to enable debugging in your moodle instance (Site Administration > Development > Debugging > Debug messages change to  Developer) and provide a full trace that comes with this error?

**Comment by mrkskwsnck** [comment]
I stumbled over the same bug. Below follows the complete debug message:

```
Exception - Class 'assignsubmission_maharaws\moodle_exception' not found

[More information about this error](https://docs.moodle.org/311/de/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 65 of /mod/assign/submission/maharaws/classes/mahara_oauth.php: Error thrown
    line 316 of /mod/assign/submission/maharaws/locallib.php: call to assignsubmission_maharaws\mahara_oauth->request()
    line 227 of /mod/assign/submission/maharaws/locallib.php: call to assign_submission_maharaws->webservice_call()
    line 1279 of /mod/assign/locallib.php: call to assign_submission_maharaws->save_settings()
    line 755 of /mod/assign/locallib.php: call to assign->update_plugin_instance()
    line 43 of /mod/assign/lib.php: call to assign->add_instance()
    line 128 of /course/modlib.php: call to assign_add_instance()
    line 168 of /course/modedit.php: call to add_moduleinfo()
```

Unfortunately, I was not able to fix my issue following @linsharon's document :-(

**Comment by danmarsden** [comment]
Thanks for providing that trace - I'm not convinced that @linsharon's document is related to this particular error - it occurs when the webservice call fails but instead of showing a useful error message it's showing you that exception. I've just fixed the path to the exception in the code via 587fb0b4976c3a888a40a64be1efe2abf5b10fc0 but now it will just show the error "'webservice call was not successful" - I suspect something else is still going on so I've left this open.

**Comment by linsharon** [comment]
i think one possibility is the versions of moodle and mahara. I updated both instances to their latest versions, and re-installed the plugin, and the problem went away. the documentation can be found in two documents:
https://github.com/linsharon/moodle_mahara_admin/blob/master/Bug%20fixing%20%231%20admin%20unable%20to%20view%20mahara%20assignment%20submissions.pdf
https://github.com/linsharon/moodle_mahara_admin/blob/master/Bug%20fixing%20%232%20teacher%20cannot%20create%20mahara%20assignment%20in%20course.pdf
anyway, after the above procedure, my instances went smoothly as for mahoodle integration.

**Comment by danmarsden** [comment]
Thanks @linsharon I'm going to close this one off for now as it sounds like you performed multiple steps to fix yours and we've fixed the class not found error now.
@mrkskwsnck - I suspect something else is going on with the connection between your moodle and mahara and it's failing to connect but with the latest code it will provide some cleaner error messages.

**Comment by linsharon** [comment]
thanks Dan!

**Comment by mrkskwsnck** [comment]
> Thanks for providing that trace - I'm not convinced that @linsharon's document is related to this particular error - it occurs when the webservice call fails but instead of showing a useful error message it's showing you that exception. I've just fixed the path to the exception in the code via [587fb0b](https://github.com/catalyst/moodle-assignsubmission_maharaws/commit/587fb0b4976c3a888a40a64be1efe2abf5b10fc0) but now it will just show the error "'webservice call was not successful" - I suspect something else is still going on so I've left this open.

@danmarsden I confirm your patch fixed my issue.

The real cause for my issue is the following now—as you suspected.

```
error/Error when connecting to Mahara web services. error/webservice call was not successful Check that URL and OAuth credentials are correct and that there is a valid SSL certificate if HTTPS is used. Also check that the correct functions are assigned to the OAuth access.

[More information about this error](https://docs.moodle.org/311/de/error/moodle/Error%20when%20connecting%20to%20Mahara%20web%20services.%20error/webservice%20call%20was%20not%20successful%20Check%20that%20URL%20and%20OAuth%20credentials%20are%20correct%20and%20that%20there%20is%20a%20valid%20SSL%20certificate%20if%20HTTPS%20is%20used.%20Also%20check%20that%20the%20correct%20functions%20are%20assigned%20to%20the%20OAuth%20access.)
Debug info:
Error code: Error when connecting to Mahara web services. error/webservice call was not successful
Check that URL and OAuth credentials are correct and that there is a valid SSL certificate if HTTPS is used. Also check that the correct functions are assigned to the OAuth access.
$a contents:
Stack trace:

    line 497 of /lib/setuplib.php: moodle_exception thrown
    line 1280 of /mod/assign/locallib.php: call to print_error()
    line 755 of /mod/assign/locallib.php: call to assign->update_plugin_instance()
    line 43 of /mod/assign/lib.php: call to assign->add_instance()
    line 128 of /course/modlib.php: call to assign_add_instance()
    line 168 of /course/modedit.php: call to add_moduleinfo()
```

Thank you very much! Now, I can work with this further.
