### ISSUE TITLE
Link to portfolio goes to front page of Mahara if not already logged in

### ISSUE THREAD

**Issue by thepurpleblob** [catalyst/moodle-assignsubmission_maharaws#48]
To reproduce...

- Set up a Moodle assignment with the Mahara link
- Get a student to make a submission
- Open a new browser (definitely not logged in to Mahara). Go to the assignment submissions listing as a Teacher and click the link to the student's Portfolio
- It doesn't - it goes to the Mahara front page
- on subsequent clicks it works fine. 

This is probably related to https://github.com/catalyst/moodle-assignsubmission_maharaws/issues/38

**Comment by thepurpleblob** [comment]
This seems to have got worse. We're now seeing Assignments were the links refuse to go to anything other than the front page. I really haven't got a clue how to debug this further.

**Comment by anitsirk** [comment]
Thank you for the report. We'll look into it.

**Comment by thepurpleblob** [comment]
To be (slightly) more useful. We tested this a lot and (apart from original issue) didn't find an issue. Now real users have got to it, we're getting some Moodle assignments that consistently drop to the Mahara front page. It still works fine when we create test Assignments. There must be some difference but we've not tracked down what it is yet.

**Comment by thepurpleblob** [comment]
After more testing - we're pretty sure that the problem is Smart Evidence. If the collection that the student is submitting to Moodle has a Smart Evidence framework selected, then it breaks. The link takes the teacher to the Mahara home page rather than the selected portfolio. 

In our testing this is quite consistent (Mahara 22.04.2)

**Comment by anitsirk** [comment]
Thanks for the additional testing. Our testing should then involve:

- single page
- collection
- collection with SmartEvidence (to be allowed in institution settings)
- collection with portfolio completion (to be allowed in institution settings)

I added the portfolio completion because that overview page is similar to SmartEvidence.

**Comment by anitsirk** [comment]
We already had a [bug report for Mahara on that](https://bugs.launchpad.net/mahara/+bug/1972912). Adding the link here for cross-reference.

**Comment by fergus-catalyst** [comment]
A patch has been added for review on Mahara that addresses this issue. See the notes on https://bugs.launchpad.net/mahara/+bug/1972912 for a link to the patch in progress.

**Comment by danmarsden** [comment]
This looks like it was an issue upstream (in mahara) and  afix has been released there... on that basis, closing this one off but please let me know if I've missed anything.
