### ISSUE TITLE
latest version of Mahara assign submission (2021112200) displays 'Archive when graded' option even when Mahara submission type is not selected.

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [catalyst/moodle-assignsubmission_maharaws#49]
After updating to the latest version of the plugin (2021112200) Assignments are displaying the 'Archive when graded' option even when Mahara submission type is not selected. Tested on moodle 3.11.9.

This will likely confuse users.

**How to reproduce**

- install latest mahara submission plugin (version number 2021112200) into moodle
- no settings need to be updated
- create a new assignment in a moodle course
- scroll down to 'Submission types', Mahara should not be selected by default
- the option 'Archive when graded' select is displayed even without the mahara option selected
- selecting mahara displays the other mahara options - url, key, secret and lock options
- deselecting mahara hides the above options but the 'Archive when graded' option persists

**Expected behaviour**
Without mahara selected in the 'Submission types' all mahara sub options would not be displayed. Selecting mahara in 'Submission types' would be displayed. Deselecting mahara again will hide all mahara options.

**Comment by james-pearce-bath-ac** [comment]
Hi, Is this issue on the roadmap to be investigated? We are keen to deploy the plugin to our Live Moodle, but want to avoid confusing users.

**Comment by danmarsden** [comment]
Hey James - I've just pushed a fix for that into the repo here. - hope that helps! :-)
