### ISSUE TITLE
If capability assignsubmission/maharaws:configure is not set then creating assignment fails horribly

### ISSUE THREAD

**Issue by thepurpleblob** [catalyst/moodle-assignsubmission_maharaws#50]
To reproduce...

Tested with Moodle 3.11.11 and latest version of plugin

- "vanilla" install of maharaws
- setup global parameters and set force_global_credentials to on
- create a test course and assign a teacher (make sure they are *only* a teach - not Manager etc)
- log in as them and create an Assignment with mahara enabled
- save assignment form

"error/Error when connecting to Mahara web services. error/webservice call was not successful Check that URL and OAuth credentials are correct and that there is a valid SSL certificate if HTTPS is used. Also check that the correct functions are assigned to the OAuth access."

Enable the assignsubmission/maharaws:configure capability for teachers and it now works fine. 

Analysis...

In locallib.php, function save_settings() the settings for the instance are only saved if you have this capability. The function then goes on to "Test mahara connection". When the web service code tries to get the url using $this->get_config("url") it fails as there is no url in the instance settings. 

I'm not sure what the intention of that capability is but if it's necessary to use the functionality then it needs to be checked properly in the Assignment settings form.

**Comment by danmarsden** [comment]
Thanks Howard! - I'll see if we can find someone here to tidy that up a bit, hope you have a good christmas break!

**Comment by anitsirk** [comment]
There may be more information in [Howard's forum posts](https://mahara.org/interaction/forum/topic.php?id=9231&post=36407).

**Comment by aneno-m-e** [comment]
This issue has been caused by the implementation of the assignsubmission/maharaws:configure capability in #7 . It changed the form so that credentials would not be added to the form for users without the capability. However, it didn't add a way to retrieve the forced global credentials to allow the connection test to Mahara to pass.

PR #51 addresses this issue.
