### ISSUE TITLE
Test the plugin with PHP 8.1

### ISSUE THREAD

**Issue by anitsirk** [catalyst/moodle-assignsubmission_maharaws#59]
We need to test if it works out of the box with PHP 8.1 or if there are any changes required.

**Comment by danmarsden** [comment]
just a quick note to state that no lint errors were detected in php 8.1, but haven't tested it directly yet.

**Comment by danmarsden** [comment]
The Moodle side seems to work as expected - closing this off now as PHP 8.1 testing is now complete.

Note: we also tested this with the upcoming Moodle 4.3 release and found it to be working there too!
