### ISSUE TITLE
Search field seems to be defunct

### ISSUE THREAD

**Issue by anitsirk** [catalyst/moodle-assignsubmission_maharaws#67]
Reported by Richard van Iwaarden in the [Mahara Git](https://git.mahara.org/catalyst/mahara/-/issues/126)

The Search has a field, but no submit button. It also doesn't submit a search if you type something to search for and press enter. Pressing enter will lead to submitting an empty portfolio to Moodle, resulting in an error.

![screenshot](https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/1209346/f9685d86-1b08-4c71-b4a8-b896b9dd8eff)

**Comment by danmarsden** [comment]
Thanks Kristina, Is that search supposed to do anything? - can I just remove it from the UI?

**Comment by danmarsden** [comment]
looks like it was just a remnant from the transition from the old mnet plugin and it definitely wasn't doing anything so I've removed it.

**Comment by anitsirk** [comment]
Thanks, @danmarsden. I do not know if it every worked in the MNet edition. Removing it (for the time being) sounds sensible.

**Comment by Richardvi** [comment]
@danmarsden thanks, this helps our students a lot. They ended up submitting nothing every time they tried to search.
