### ISSUE TITLE
Exception - Argument 1 passed to assign::calculate_properties() 

### ISSUE THREAD

**Issue by sharpchi** [catalyst/moodle-assignsubmission_maharaws#70]
I'm getting the following error when trying to create an assignment. I haven't configured maharaws, which may be something to do with it. I think it's related to a recent fix #68 which has added a call to $assignment->get_instance() perhaps on something that doesn't yet exist.

The error goes away when I disable the submission plugin

![image](https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/3774280/55e3f92e-a564-41d3-85d1-49c572b23dae)

**Comment by danmarsden** [comment]
Thanks for the report! - I've just pushed an untested PR (#71) that should fix this - let me know if you get a chance to test it otherwise I'll try to do that soon and merge it in.

thanks!
