### ISSUE TITLE
Link to portfolio in 'Draft' on the assignment overview page goes to the Mahara dashboard

### ISSUE THREAD

**Issue by anitsirk** [catalyst/moodle-assignsubmission_maharaws#78]
When the assignment submission status is in "Draft (not submitted)", the link of the submitted work goes to the Mahara dashboard instead of the Mahara page / collection that the studen submitted.

### Steps to replicate in Moodle

1. Create an assignment with Mahara as submission type, e.g. https://domain/course/modedit.php?update=230510&return=1
2. Log in as Student
3. Click on assignment created in step 1
4. Click "Add submission"
5. Select Mahara page for submission, e.g. "Untitled v. 2" > Save changes
6. Under 'Submission status' > Click on "Untitled v. 2" - screenshot below

![submission](https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/1209346/b4ae645e-85fd-483c-8ab3-dc59c8decec7)

### Results

- Expected result: Opens "Untitled v. 2" in a new tab
- Current behaviour: Opens Mahara dashboard - screenshot attached.

**Comment by anitsirk** [comment]
This is actually not a problem with Mahara main and Moodle 4.1. Might have only been an issue with an older version of Mahara.

**Comment by tuanngocnguyen** [comment]
Hi @anitsirk ,

The issue occurs when using Mahara 21.10, with cleanurl enabled. The error does not occur on Mahara 23.04
It is fixed after backporting this commit : https://git.catalyst-au.net/upstream/catalyst-mahara/-/commit/75fd155ac5a93f2e0cdf708ae8a67a9198b611aa
